version: '3.8'

services:
    postgres:
        image: postgres:alpine
        container_name: postgres_container
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  streamlit:
    image: python:3.12-slim
    container_name: streamlit_container
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && streamlit run app.py"
    ports:
      - "8501:8501"
    depends_on:
      - postgres

volumes:
  postgres_data:
